server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 100
      test-while-idle: true
      validation-query: SELECT 1
      min-evictable-idle-time-millis: 300000 # 5分鐘空閑則回收
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
#配置细粒度的Ribbon规则（配置属性方式）,这里指定了客户端
user-center:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.gyh.contentcenter.config.NacosWeightedRule
ribbon:
  eager-load:
    enabled: true #设置为饥饿加载，默认是false，也就是懒加载，故第一次请求的时候响应会比较慢
    clients: user-center #为那些名称的Ribbon客户端指定饥饿加载，多个用逗号分隔